language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached

before_script:
  - printf "\n" | pecl install -f memcache-3.0.8
  - composer self-update
  - phpenv config-add travisconfig.ini
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit -c phpunit_ci.xml
