language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached

before_script:
  - pecl list
  - pecl install -f memcache-3.0.8
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - phpenv config-add travisconfig.ini

script: vendor/bin/phpunit -c phpunit_ci.xml
